services:
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - './api:/var/www/html'
    networks:
      budget-calculator-network:
        ipv4_address: 172.84.24.11

  vue:
    image: node:latest
    working_dir: /app
    volumes:
      - "./vue/public:/app/public"
      - "./vue/src:/app/src"
      - "./vue/index.html:/app/index.html"
      - "./vue/package.json:/app/package.json"
      - "./vue/vite.config.js:/app/vite.config.js"
    command: sh -c "npm install && npm run serve"
    networks:
      budget-calculator-network:
        ipv4_address: 172.84.24.12

  mysql:
    image: mysql:latest
    command: --init-file /data/application/init.sql
    volumes:
      - './db/mysql_data:/var/lib/mysql'
      - './db/init.sql:/data/application/init.sql'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Muscat
    networks:
      budget-calculator-network:
        ipv4_address: 172.84.24.13

  nginx:
    image: nginx:latest
    volumes:
      - './api:/var/www/html'
      - './nginx/conf.d:/etc/nginx/conf.d'
    networks:
      budget-calculator-network:
        ipv4_address: 172.84.24.14

networks:
  budget-calculator-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.84.24.0/24
